version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "announcement"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zmxtmnifvo3i"
s3_prefix = "announcement"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"v1\""
